name: Build and deploy wordpress plugin

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of the container
        required: true
        type: string
      is_stable_release:
        description: Is this a stable release?
        required: true
        default: false
        type: boolean

  workflow_call:
    inputs:
      version:
        required: true
        type: string
      is_stable_release:
        required: true
        type: boolean

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0
          run_install: false

      - name: Install SVN
        run: sudo apt-get install subversion

      - name: Install wp-cli
        uses: godaddy-wordpress/setup-wp-cli@1

      - name: Install widget dependencies
        run: pnpm install

      - name: Install WordPress plugin dependencies
        working-directory: wordpress-plugin/calculator-dostanesie-pl
        run: pnpm install

      - name: Build widget for WordPress
        run: pnpm run widget:build:wordpress

      - name: Generate WordPress translations
        working-directory: wordpress-plugin/calculator-dostanesie-pl
        run: |
          pnpm run wordpress-plugin:generate-mo
          pnpm run wordpress-plugin:generate-json

      - name: Build WordPress plugin
        working-directory: wordpress-plugin/calculator-dostanesie-pl
        run: pnpm run wordpress-plugin:build

      - name: Prepare zip of WordPress plugin
        working-directory: wordpress-plugin/calculator-dostanesie-pl
        run: pnpm run wordpress-plugin:plugin-zip

      - name: Checkout svn repo
        run: svn checkout https://plugins.svn.wordpress.org/dostanesie-pl-calculator --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }} svn/

      - name: Unzip WordPress plugin to svn trunk
        run: |
          rm -rf svn/trunk/*
          unzip wordpress-plugin/calculator-dostanesie-pl/calculator-dostanesie-pl.zip -d svn/trunk
          mv svn/trunk/calculator-dostanesie-pl/* svn/trunk/
          rmdir svn/trunk/calculator-dostanesie-pl/

      - name: Check if tag already exists
        if: ${{ inputs.is_stable_release }}
        run: |
          if [ -d "svn/tags/${{ inputs.version }}" ]; then
            echo "Tag ${{ inputs.version }} already exists in SVN repo. Aborting."
            exit 1
          fi

      - name: Unzip WordPress plugin to svn tag
        if: ${{ inputs.is_stable_release }}
        run: |
          unzip wordpress-plugin/calculator-dostanesie-pl/calculator-dostanesie-pl.zip -d svn/tags/${{ inputs.version }}
          mv svn/tags/${{ inputs.version }}/calculator-dostanesie-pl/* svn/tags/${{ inputs.version }}/
          rmdir svn/tags/${{ inputs.version }}/calculator-dostanesie-pl/

      - name: Check svn status
        working-directory: svn/
        run: svn status

      - name: Add all changes to svn
        working-directory: svn/
        run: |
          svn add --force .
          svn status

      - name: Commit changes to svn
        working-directory: svn/
        run: |
          svn commit -m "chore: release version ${{ inputs.version }}" --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }} --no-auth-cache
